apiVersion: v1
kind: Pod
metadata: 
  name: stress
spec:
  containers:
  - image: satishlanka/stress:latest
    imagePullPolicy: Always
    name: stress
    command: ["sleep","200"]
    resources:
      limits: 
        cpu: "200mi"
        memory: "300Mi"
      requests:
        cpu: "150m"
        memory: "200Mi"
      